use serde::{Deserialize, Serialize};
use std::fmt;

/// Result received from the Physics Engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PhysicsResult {
    pub device_id: String,
    pub command: String,
    
    #[serde(default)]
    pub pressure: Option<f64>,

    #[serde(default)]
    pub flow: Option<f64>,

    /// Pump speed in RPM.
    pub pump_speed: Option<f64>,

    /// Overall physics status.
    pub status: PhysicsStatus,

    /// Generic value used by the original Decision Engine tests.
    #[serde(default)]
    pub value: f64,

    /// Unit associated with the generic value.
    #[serde(default)]
    pub unit: String,

    /// Predicted pressure from the Physics Engine.
    #[serde(default)]
    pub predicted_pressure: Option<f64>,

    /// Maximum safe pressure.
    #[serde(default)]
    pub pressure_limit: Option<f64>,

    /// Predicted flow from the Physics Engine.
    #[serde(default)]
    pub predicted_flow: Option<f64>,

    /// Maximum safe flow.
    #[serde(default)]
    pub flow_limit: Option<f64>,

    /// Maximum safe pump speed.
    #[serde(default)]
    pub pump_speed_limit: Option<f64>,
}

/// Status reported by the Physics Engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "UPPERCASE")]
pub enum PhysicsStatus {
    Safe,
    Warning,
    CatastrophicFailure,
}

/// Final decision generated by the Decision Engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "UPPERCASE")]
pub enum Decision {
    Allow,
    Drop,
}

impl fmt::Display for Decision {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Decision::Allow => write!(f, "ALLOW"),
            Decision::Drop => write!(f, "DROP"),
        }
    }
}

/// Reason for the generated decision.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum DecisionReason {
    PhysicsStatusSafe,
    PhysicsStatusWarning,
    PhysicsStatusCritical,
    CatastrophicFailure,
    PressureLimitExceeded,
    FlowLimitExceeded,
    PumpSpeedExceeded,
    InvalidPhysicalState,
    InvalidInput,
    MissingPhysicsData,
    UnknownPhysicsStatus,
}

impl DecisionReason {
    /// Returns a human-readable explanation for the decision reason.
    pub fn description(&self) -> &'static str {
        match self {
            DecisionReason::PhysicsStatusSafe => {
                "Physics Engine reports a safe physical state"
            }
            DecisionReason::PhysicsStatusWarning => {
                "Physics Engine reports a warning condition"
            }
            DecisionReason::PhysicsStatusCritical => {
                "Physics Engine reports a critical condition"
            }
            DecisionReason::CatastrophicFailure => {
                "Catastrophic physical failure detected"
            }
            DecisionReason::PressureLimitExceeded => {
                "Pressure safety limit exceeded"
            }
            DecisionReason::FlowLimitExceeded => {
                "Flow safety limit exceeded"
            }
            DecisionReason::PumpSpeedExceeded => {
                "Pump speed safety limit exceeded"
            }
            DecisionReason::InvalidPhysicalState => {
                "Invalid physical state detected"
            }
            DecisionReason::InvalidInput => {
                "Invalid input provided"
            }
            DecisionReason::MissingPhysicsData => {
                "Required Physics Engine data is missing"
            }
            DecisionReason::UnknownPhysicsStatus => {
                "Unknown Physics Engine status"
            }
        }
    }
}

/// Final result returned by the Decision Engine.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DecisionResult {
    pub device_id: String,
    pub decision: Decision,
    pub reason: DecisionReason,
}