from dataclasses import dataclass
from typing import List


@dataclass(frozen=True)
class DecisionData:
    """Represents a security decision generated by VoltGuard."""

    decision_id: str
    timestamp: str
    title: str
    decision: str
    severity: str
    confidence: int
    asset: str
    source: str
    category: str
    reason: str
    recommended_action: str


class MockDecisionProvider:
    """Temporary provider for dashboard development."""

    def get_decisions(self) -> List[DecisionData]:
        """Return simulated security decisions."""

        return [
            DecisionData(
                decision_id="DEC-0001",
                timestamp="21:48:32",
                title="Unauthorized PLC Write",
                decision="BLOCK",
                severity="CRITICAL",
                confidence=96,
                asset="Main Process PLC",
                source="10.10.20.99",
                category="COMMAND ANOMALY",
                reason=(
                    "Write operation originated from "
                    "an untrusted source."
                ),
                recommended_action=(
                    "Block the source and investigate "
                    "the originating host."
                ),
            ),
            DecisionData(
                decision_id="DEC-0002",
                timestamp="21:45:19",
                title="Abnormal Modbus Frequency",
                decision="MONITOR",
                severity="HIGH",
                confidence=89,
                asset="Packaging PLC",
                source="10.10.20.80",
                category="TRAFFIC ANOMALY",
                reason=(
                    "Modbus request frequency exceeded "
                    "the established baseline."
                ),
                recommended_action=(
                    "Continue monitoring and inspect "
                    "the source endpoint."
                ),
            ),
            DecisionData(
                decision_id="DEC-0003",
                timestamp="21:41:05",
                title="Cross-Zone Communication",
                decision="INVESTIGATE",
                severity="MEDIUM",
                confidence=82,
                asset="Engineering Workstation",
                source="10.10.20.30",
                category="POLICY VIOLATION",
                reason=(
                    "Communication crossed from the "
                    "supervisory zone into the field zone."
                ),
                recommended_action=(
                    "Verify whether the communication "
                    "was authorized."
                ),
            ),
            DecisionData(
                decision_id="DEC-0004",
                timestamp="21:37:44",
                title="Unexpected DNP3 Command",
                decision="BLOCK",
                severity="HIGH",
                confidence=91,
                asset="Water Treatment RTU",
                source="10.10.20.70",
                category="PROTOCOL ANOMALY",
                reason=(
                    "Command pattern does not match "
                    "the expected RTU profile."
                ),
                recommended_action=(
                    "Block the source and validate "
                    "the RTU operational state."
                ),
            ),
            DecisionData(
                decision_id="DEC-0005",
                timestamp="21:32:16",
                title="New Device Detected",
                decision="MONITOR",
                severity="MEDIUM",
                confidence=76,
                asset="Unknown Device",
                source="10.10.20.77",
                category="ASSET ANOMALY",
                reason=(
                    "Previously unknown device appeared "
                    "on the control network."
                ),
                recommended_action=(
                    "Identify and authorize the device."
                ),
            ),
            DecisionData(
                decision_id="DEC-0006",
                timestamp="21:28:51",
                title="Sensor Communication Loss",
                decision="MONITOR",
                severity="LOW",
                confidence=94,
                asset="Pressure Sensor",
                source="10.10.20.42",
                category="AVAILABILITY",
                reason=(
                    "Sensor communication stopped "
                    "within the expected interval."
                ),
                recommended_action=(
                    "Check device availability "
                    "and connectivity."
                ),
            ),
        ]

    def get_risk_score(
        self,
        decisions: List[DecisionData],
    ) -> int:
        """Calculate a simple dashboard risk score."""

        if not decisions:
            return 0

        weights = {
            "CRITICAL": 100,
            "HIGH": 75,
            "MEDIUM": 45,
            "LOW": 20,
        }

        total = sum(
            weights.get(
                decision.severity,
                0,
            )
            for decision in decisions
        )

        maximum = len(decisions) * 100

        score = int(
            (total / maximum) * 100
        )

        return min(
            max(score, 0),
            100,
        )