from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict


@dataclass(frozen=True)
class PacketEvent:
    """Represents a packet received from the packet interceptor."""

    timestamp: str
    source_ip: str
    destination_ip: str
    protocol: str
    source_port: int
    destination_port: int
    packet_size: int
    interface: str


@dataclass(frozen=True)
class ThreatEvent:
    """Represents a threat identified by the physics engine."""

    timestamp: str
    threat_id: str
    asset: str
    severity: str
    anomaly_score: float
    category: str
    description: str


@dataclass(frozen=True)
class DecisionEvent:
    """Represents a decision generated by the decision engine."""

    timestamp: str
    decision_id: str
    decision: str
    severity: str
    confidence: int
    asset: str
    reason: str


@dataclass(frozen=True)
class IntegrationEvent:
    """Generic event exchanged between VoltGuard modules."""

    event_type: str
    timestamp: str
    source_module: str
    payload: Dict[str, Any]

    @classmethod
    def create(
        cls,
        event_type: str,
        source_module: str,
        payload: Dict[str, Any],
    ) -> "IntegrationEvent":
        """Create a timestamped integration event."""

        return cls(
            event_type=event_type,
            timestamp=datetime.now().strftime(
                "%H:%M:%S"
            ),
            source_module=source_module,
            payload=payload,
        )